name: toh
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.64.2 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.3+1
  build_web_compilers: ^1.0.0
  pageloader: ^3.1.0
  test: ^1.3.0
